name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install LuaJIT
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit
      - name: Get workspace for building
        uses: actions/checkout@v2
        with:
          repository: eutaxy/workspace
          path: .
          ssh-key: ${{ secrets.WS_PAT }}
      - name: output current directory
        uses: actions/checkout@v2
        with:
          path: src/exy_core
      - name: Building the project
        run: |
          bun install
          bun run build
      - name: Zip the build
        run: |
          cd .dist/server-data/resources/exy_core
          zip -r exy_core.zip *
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: release-${{ github.sha }}
          files: .dist/server-data/resources/exy_core/exy_core.zip
